# Generated by Django 4.2.7 on 2023-11-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_description1',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_description2',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
